### ISSUE TITLE
[wayland] crash gnome shell session when capture QR code

### ISSUE THREAD

**Issue by Dea1993** [bilelmoussaoui/Authenticator#50]
**Reporter info**

 ```
 * Distribution - Fedora 27
 * Desktop environment - Gnome shell 3.26.2
 ```

**Authenticator version**
0.2.1 (installed with flatpak from flathub)

**Actual issue**
when i press QR code button on gnome shell with a wayland session, the session crash and I return to lockscreen

**Steps to reproduce (if you knew)**
Add a new account, select a service/site, click next, and then click on QR code button

**Comment by bilelmoussaoui** [comment]
See https://github.com/bilelmoussaoui/Authenticator/issues/50

**Comment by bilelmoussaoui** [comment]
The issue here is that Wayland doesn't allow an application to take a screenshot of another application. GNOME screenshot (used to take a screenshot) fallbacks to Xorg in order to take that screenshot, which doesn't work perfectly :(
GNOME provides already a DBus API to take a screenshot of any application using GNOME Shell itself. But that won't work on any other DE. There's no standard DBus API for that. There's just no way to do it in a way that will work everywhere :(
Freedesktop should add a way to do the same things soon.  But it's not the case yet :( 

For now, I see only two options:
- Disable Wayland by default (force Xorg) for the application itself.
- Mark the application as "GNOME" only app. 

I'm going to take a deeper look at this and try to add a default Xorg implementation without using gnome-screenshot and keep the GNOME Screenshot API for Wayland. If none is supported on the current DE the user is using the QR scanner button will be hidden

**Comment by SolarLiner** [comment]
Another option would be to activate the feature only in GNOME, with a nice explanation somewhere that you can refer users to inform them. This allows using GNOME Shell's feature while allowing users in other DEs to still use the app (albeit without the QR scan feature).

This exposes the problem of having to implement each DE's Wayland support separately, while a standardized method surfaces.

**Comment by bilelmoussaoui** [comment]
Fixed on master
