### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by aswolf2010** [bilelmoussaoui/Authenticator#69]
Hi,

First, many thanks for developing authenticator!! I am newb in linux and github, I am trying to have authenticator in two different computers to generate tokens for the same online account but it does only work in one of them. I am not sure if its posible, but it would be great have that feature.

Thanks

**Comment by SolarLiner** [comment]
I think this is a design limitation of 2FA rather than the particular application.

I myself, have three different sources of auth codes (Google Authenticator, this app and the KeePass TOTC); and you have to add the authentication key (or scan the QR codes) for all your authenticator apps at once, because the given key (or QR code) will not be given to you again.

**Comment by bilelmoussaoui** [comment]
As @SolarLiner  explained, it's impossible to do.
