### ISSUE TITLE
How to enter custom application?

### ISSUE THREAD

**Issue by boweevil** [bilelmoussaoui/Authenticator#79]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.30-1
 * Desktop environment - Gnome 3.28.2
 ```

**Authenticator version 0.2.2.1**

**Actual issue**
Unable to determine how to add OpenVPN.  I have a QR code and can also use the token.  How would I add an entry for a custom (not public, non-website) application?  I noticed that the database comes from https://github.com/2factorauth/twofactorauth.  That tool seems to be geared towards websites and does not account for any private options.

**Steps to reproduce (if you knew)**

**Other Note (feature-request, question, etc...)**

**Comment by dannosaur** [comment]
You can't. This is explictly built to provide codes from a pre-defined list of sites. This appears to be solely for the purpose of icons, which is wholely unnecessary. Even if the author were to add in OpenVPN as a provider to the list, it doesn't solve the problem, in my case as well as yours, I have a whole bunch of custom websites that have 2FA enabled, which I'd never want to add to a public list such as this one.

I have a fork which I started working on today that removes that first "select site" step. I'll submit a pull request when I'm done, but I suspect because the changes I've made are quite significant, it's unlikely that the author will accept them as-is.

If you're comfortable installing this manually, checkout my fork at https://github.com/dannosaur/Authenticator and let me know what you think.

I'd appreciate @bilelmoussaoui's feedback on this as well.

**Comment by bilelmoussaoui** [comment]
The idea behind the list of the apps is to have a list of where the user could choose. Removing it is not the best solution I guess.

I was thinking of improving the behavior a bit but I'm looking for some nice UI design to implement otherwise it will just look so ugly!

**Comment by bilelmoussaoui** [comment]
What I was thinking of is to add a "not on the list" which will let you type the provider name too. I'm reworking the main UI to make the accounts listed by the provider (Google, Amazon, Facebook...)

**Comment by dannosaur** [comment]
The list of sites serves no real purpose. Yes, a user could choose from the list, much as you could potentially turn the "provider" field on the second step into a dropdown maybe with the list, and an "Other" option, which potentially could present a text box for the user to type the provider's name into?

Right now, the fork I've got normalizes the name and will present the icon if it finds a match within the theme's icons list. Obviously this depends on the provider's name being typed (almost) exactly as it presents in the icon list, but it's a start.

**Comment by dannosaur** [comment]
That makes sense. I did think about how the icons could be incorporated without any way of selecting from a list, but I think this is the nicest solution. And if you're packaging icons with the app then you're not completely relying on the theme's icon list which I guess can be hit-and-miss depending on the system.

I've already stripped out the first step and made some other changes here and there to make it a bit nicer (altered slightly how the record is stored in the keyring so the record isn't blank, it has some meaning now). Also looking at incorporating #26 as well because I think that's a neat idea and has some uses.

**Comment by bilelmoussaoui** [comment]
I didn't decide to implement the terminal version yet. Because I would like to re-add (was there on old version but wasn't working that good) a way to login with a password. This way, if someone has access to your laptop/computer/phone. They wouldn't get access to the 2FA codes.

So, currently a redesigned add list would make sense before starting to implement that cli version.

**Comment by dannosaur** [comment]
I've branched that off away from my master branch, so the UI changes I've made are separate to the terminal application that I'm playing around with. To be fair I only started to do that because I was bored :)

**Comment by bilelmoussaoui** [comment]
Perfect! Will be waiting for that PR :+1:

**Comment by dannosaur** [comment]
It's pretty much exactly what I had stashed in a branch that I was polishing off before sending the PR. Same idea, except I had a "Not Listed" option present a free text box (primarily because I wasn't aware you could get the entered text out of the combo box if there was no selected iteration). Yours is better in that respect.

**Comment by bilelmoussaoui** [comment]
Still not sure about one thing, either to make that window resizable or not? Other than this, everything looks and works pretty okay for now.

**Comment by bilelmoussaoui** [comment]
Fixed on master.

**Comment by boweevil** [comment]
Perfect!  Thank you!
